git submodule add https://github.com/vim-scripts/argtextobj.vim.git
git submodule add https://github.com/bkad/CamelCaseMotion.git
git submodule add https://github.com/ctrlpvim/ctrlp.vim.git
git submodule add https://github.com/Konfekt/FastFold.git
git submodule add https://github.com/vim-scripts/indentpython.vim.git
git submodule add https://github.com/Rykka/riv.vim.git
git submodule add https://github.com/tmhedberg/SimpylFold.git
git submodule add https://github.com/vim-syntastic/syntastic.git
git submodule add https://github.com/vim-airline/vim-airline.git
git submodule add https://github.com/vim-airline/vim-airline-themes.git
git submodule add https://github.com/tpope/vim-commentary.git
git submodule add https://github.com/tpope/vim-fugitive.git
git submodule add https://github.com/jonathanfilip/vim-lucius
git submodule add https://github.com/tpope/vim-sensible.git
git submodule add https://github.com/tpope/vim-surround.git
git submodule add https://github.com/kana/vim-textobj-entire.git
git submodule add https://github.com/kana/vim-textobj-user.git
git submodule add https://github.com/cespare/vim-toml.git
git submodule add https://github.com/bronson/vim-trailing-whitespace.git
git submodule add https://github.com/scrooloose/nerdtree.git
git submodule add https://github.com/davidhalter/jedi-vim.git
git submodule add https://github.com/ervandew/supertab.git
git submodule add https://github.com/jeffkreeftmeijer/vim-numbertoggle.git
